#ifndef EVOAI_SELF_ORGANIZING_MAP_HPP
#define EVOAI_SELF_ORGANIZING_MAP_HPP

#include <cstddef>
#include <cmath>
#include <limits>
#include <random>
#include <stdexcept>
#include <algorithm>
#include <iostream>
#include <optional>
#include <utility>
#include <vector>

#include <JsonBox.h>

#include <EvoAI/Schedulers.hpp>
#include <EvoAI/Utils/TypeUtils.hpp>
#include <EvoAI/Utils/RandomUtils.hpp>

namespace EvoAI{
    /**
     * @brief Euclidean distance between two feature vectors.
     * @details
     *  Default DistanceFn for SelfOrganizingMap. Fulfills
     *  meta::distance_metric_v<EuclideanDistance>.
     *
     *  Assumes a.size() == b.size()
     */
    struct EuclideanDistance final{
        /**
         * @brief computes the euclidean distance between a and b.
         * @param a const std::vector<double>&
         * @param b const std::vector<double>&
         * @return double
         */
        double operator()(const std::vector<double>& a, const std::vector<double>& b) const noexcept;
    };

    /**
     * @class SelfOrganizingMap
     * @brief Generic Kohonen Self-Organizing Map over std::vector<double> feature vectors.
     * @tparam DistanceFn distance metric between two feature vectors, defaults to EuclideanDistance.
     * @details
     *  Domain-agnostic: this class does not know or care what produced a
     *  sample vector, image pixels, genome weights, anything
     *  reducible to a std::vector<double> works identically. Feature
     *  extraction is entirely the caller's responsibility, done before ever
     *  calling train() or classify().
     *
     *  DistanceFn needs to fulfill meta::distance_metric_v<DistanceFn>: <br />
     *      DistanceFn has a double operator()(const std::vector<double>&, const std::vector<double>&) const noexcept <br />
     *
     */
    template<class DistanceFn = EuclideanDistance>
    class SelfOrganizingMap final{
        public:
            static_assert(meta::distance_metric_v<DistanceFn>, "DistanceFn requires to fulfill meta::distance_metric_v, more info at Utils/TypeUtils.hpp");
            /**
             * @brief constructor
             * @param width std::size_t grid width, must be > 0
             * @param height std::size_t grid height, must be > 0
             * @param inputDim std::size_t dimension every feature vector given to
             *        train()/classify() must have, must be > 0
             * @param toroidal bool whether the grid wraps around at the edges (default true)
             * @param distance DistanceFn distance metric to use (default EuclideanDistance{})
             * @throws std::invalid_argument if width, height or inputDim is 0 -
             *         this is a structural/construction-time error (matches
             *         NeuralNetwork's throwing convention for the same kind of
             *         problem), not a runtime-data-quality one.
             */
            SelfOrganizingMap(std::size_t width, std::size_t height, std::size_t inputDim,
                               bool toroidal = true, DistanceFn distance = DistanceFn{});
            /**
             * @brief constructor for a JsonBox::Object saved with toJson()
             * @param o JsonBox::Object
             * @throws std::invalid_argument if width, height or inputDim is 0, or
             *         if the saved weights array's size doesn't match width*height*inputDim.
             */
            SelfOrganizingMap(JsonBox::Object o);
            /**
             * @brief checks whether sample is usable by train()/classify(): its
             *        size matches getInputDim() and every element is finite
             *        (not NaN/Inf).
             * @param sample const std::vector<double>&
             * @return bool
             */
            bool validateSample(const std::vector<double>& sample) const noexcept;
            /**
             * @brief trains the map with a batch of samples over a number of epochs.
             * @details
             *  Samples that fail validateSample() are skipped (and logged to
             *  std::cerr with their index) rather than aborting the whole run -
             *  a batch generated by an external, automated pipeline (e.g. many
             *  calls to a Python feature-extraction function) can reasonably be
             *  expected to have the odd malformed entry, and losing the entire
             *  training run over one bad sample is worse than skipping it.
             *  Sample order is reshuffled every epoch. LRAlgo/RadiusAlgo are
             *  chained across epochs (each epoch's result feeds the next
             *  call), currentRadius shrinking to 0 or below (e.g. via LinearLR
             *  or enough compounding steps) is handled explicitly: the
             *  neighborhood Gaussian would otherwise divide by zero exactly at
             *  the BMU (distance 0), so at that point only the BMU itself is
             *  updated (full influence), every other node gets none.
             * @tparam LRAlgo Scheduler algorithm for the learning rate.
             * @tparam RadiusAlgo Scheduler algorithm for the neighborhood radius.
             * @param samples const std::vector<std::vector<double>>&
             * @param epochs std::size_t
             * @param baseLR double
             * @param baseRadius double
             * @param lrSchedule Scheduler<LRAlgo>
             * @param radiusSchedule Scheduler<RadiusAlgo>
             * @return std::size_t number of samples skipped for failing validateSample()
             */
            template<class LRAlgo, class RadiusAlgo>
            std::size_t train(const std::vector<std::vector<double>>& samples, std::size_t epochs,
                               double baseLR, double baseRadius,
                               Scheduler<LRAlgo> lrSchedule, Scheduler<RadiusAlgo> radiusSchedule);
            /**
             * @brief finds the Best-Matching-Unit for a sample - its grid coordinate.
             * @details This is the "species ID" for a classifier:
             *          same grid coordinate means "same species".
             * @param sample const std::vector<double>&
             * @return std::optional<std::pair<std::size_t,std::size_t>> empty if
             *         sample fails validateSample().
             */
            std::optional<std::pair<std::size_t,std::size_t>> classify(const std::vector<double>& sample) const noexcept;
            /**
             * @brief copies out node (x,y)'s prototype vector.
             *
             * @param x std::size_t
             * @param y std::size_t
             * @return std::vector<double>
             * @throws std::out_of_range if x >= getWidth() or y >= getHeight().
             */
            std::vector<double> getPrototype(std::size_t x, std::size_t y) const;
            /**
             * @brief getter for grid width
             * @return std::size_t
             */
            std::size_t getWidth() const noexcept;
            /**
             * @brief getter for grid height
             * @return std::size_t
             */
            std::size_t getHeight() const noexcept;
            /**
             * @brief getter for the dimension every feature vector must have
             * @return std::size_t
             */
            std::size_t getInputDim() const noexcept;
            /**
             * @brief converts to a JsonBox::Value
             * @return JsonBox::Value
             */
            JsonBox::Value toJson() const;
            ~SelfOrganizingMap() = default;
        private:
            /**
             * @brief flat index of dimension d of node (x,y)'s prototype vector
             *        inside m_weights. Row-major: node (x,y)'s inputDim-length
             *        vector starts at idx(x,y,0) and runs for inputDim doubles.
             */
            std::size_t idx(std::size_t x, std::size_t y, std::size_t d) const noexcept;
            /**
             * @brief grid-space distance between two nodes (not feature-space -
             *        used for the neighborhood Gaussian), accounting for
             *        toroidal wraparound if enabled.
             */
            double gridDistance(std::size_t x1, std::size_t y1, std::size_t x2, std::size_t y2) const noexcept;
            /**
             * @brief Best-Matching-Unit search over the whole grid.
             *
             * @param sample const std::vector<double>& sample to find bmu from.
             */
            std::pair<std::size_t,std::size_t> findBMU(const std::vector<double>& sample) const noexcept;
        private:
            std::size_t m_width;
            std::size_t m_height;
            std::size_t m_inputDim;
            bool m_toroidal;
            DistanceFn m_distance;
            std::vector<double> m_weights;
            mutable std::vector<double> m_scratch;
    };
    // EuclideanDistance impl
    inline double EuclideanDistance::operator()(const std::vector<double>& a, const std::vector<double>& b) const noexcept{
        double sum = 0.0;
        for(std::size_t i=0;i<a.size();++i){
            auto diff = a[i] - b[i];
            sum += diff * diff;
        }
        return std::sqrt(sum);
    }
    // SelfOrganizingMap impl
    template<class DistanceFn>
    SelfOrganizingMap<DistanceFn>::SelfOrganizingMap(std::size_t width, std::size_t height, std::size_t inputDim,
                                                       bool toroidal, DistanceFn distance)
    : m_width(width)
    , m_height(height)
    , m_inputDim(inputDim)
    , m_toroidal(toroidal)
    , m_distance(distance)
    , m_weights(width * height * inputDim)
    , m_scratch(inputDim){
        if(m_width == 0 || m_height == 0 || m_inputDim == 0){
            throw std::invalid_argument("EvoAI::SelfOrganizingMap - width, height and inputDim must all be > 0");
        }
        for(auto& w : m_weights){
            w = randomGen().random(0.0, 1.0);
        }
    }
    template<class DistanceFn>
    SelfOrganizingMap<DistanceFn>::SelfOrganizingMap(JsonBox::Object o)
    : m_width(safeParseUInt<std::size_t>(o["width"].getString()))
    , m_height(safeParseUInt<std::size_t>(o["height"].getString()))
    , m_inputDim(safeParseUInt<std::size_t>(o["inputDim"].getString()))
    , m_toroidal(o["toroidal"].getBoolean())
    , m_distance(DistanceFn{})
    , m_weights()
    , m_scratch(m_inputDim){
        if(m_width == 0 || m_height == 0 || m_inputDim == 0){
            throw std::invalid_argument("EvoAI::SelfOrganizingMap - width, height and inputDim must all be > 0");
        }
        auto weightsArr = o["weights"].getArray();
        m_weights.reserve(weightsArr.size());
        for(auto& v : weightsArr){
            m_weights.push_back(v.getDouble());
        }
        if(m_weights.size() != m_width * m_height * m_inputDim){
            throw std::invalid_argument("EvoAI::SelfOrganizingMap - saved weights size doesn't match width*height*inputDim");
        }
    }
    template<class DistanceFn>
    bool SelfOrganizingMap<DistanceFn>::validateSample(const std::vector<double>& sample) const noexcept{
        if(sample.size() != m_inputDim){
            return false;
        }
        return std::all_of(sample.begin(), sample.end(), [](double v){ return std::isfinite(v); });
    }
    template<class DistanceFn>
    template<class LRAlgo, class RadiusAlgo>
    std::size_t SelfOrganizingMap<DistanceFn>::train(const std::vector<std::vector<double>>& samples, std::size_t epochs,
                                                       double baseLR, double baseRadius,
                                                       Scheduler<LRAlgo> lrSchedule, Scheduler<RadiusAlgo> radiusSchedule){
        std::vector<std::size_t> validIndices;
        validIndices.reserve(samples.size());
        std::size_t skipped = 0u;
        for(std::size_t i=0;i<samples.size();++i){
            if(validateSample(samples[i])){
                validIndices.push_back(i);
            }else{
                std::cerr << "EvoAI::SelfOrganizingMap::train - skipping sample " << i
                          << ": expected size " << m_inputDim << ", got size " << samples[i].size();
                if(samples[i].size() == m_inputDim){
                    std::cerr << " (contains a non-finite value)";
                }
                std::cerr << "\n";
                ++skipped;
            }
        }
        if(validIndices.empty()){
            return skipped;
        }
        auto& engine = randomGen().getEngine();
        double currentLR = baseLR;
        double currentRadius = baseRadius;
        for(std::size_t epoch=0;epoch<epochs;++epoch){
            currentLR = lrSchedule.step(currentLR, epoch);
            currentRadius = radiusSchedule.step(currentRadius, epoch);
            // Fisher-Yates shuffle of validIndices, reusing the shared RNG engine.
            for(std::size_t i=validIndices.size(); i>1; --i){
                std::uniform_int_distribution<std::size_t> ud(0u, i-1);
                std::swap(validIndices[i-1], validIndices[ud(engine)]);
            }
            for(auto sampleIdx : validIndices){
                const auto& sample = samples[sampleIdx];
                auto [bmuX, bmuY] = findBMU(sample);
                for(std::size_t y=0;y<m_height;++y){
                    for(std::size_t x=0;x<m_width;++x){
                        auto gDist = gridDistance(x, y, bmuX, bmuY);
                        double influence;
                        if(currentRadius > 0.0){
                            influence = std::exp(-(gDist * gDist) / (2.0 * currentRadius * currentRadius));
                        }else{
                            influence = (gDist == 0.0) ? 1.0 : 0.0;
                        }
                        if(influence == 0.0){
                            continue;
                        }
                        for(std::size_t d=0;d<m_inputDim;++d){
                            auto weightIdx = idx(x, y, d);
                            m_weights[weightIdx] += currentLR * influence * (sample[d] - m_weights[weightIdx]);
                        }
                    }
                }
            }
        }
        return skipped;
    }
    template<class DistanceFn>
    std::optional<std::pair<std::size_t,std::size_t>> SelfOrganizingMap<DistanceFn>::classify(const std::vector<double>& sample) const noexcept{
        if(!validateSample(sample)){
            return std::nullopt;
        }
        return findBMU(sample);
    }
    template<class DistanceFn>
    std::vector<double> SelfOrganizingMap<DistanceFn>::getPrototype(std::size_t x, std::size_t y) const{
        if(x >= m_width || y >= m_height){
            throw std::out_of_range("EvoAI::SelfOrganizingMap::getPrototype - (x,y) out of range");
        }
        auto base = idx(x, y, 0);
        return std::vector<double>(m_weights.begin() + base, m_weights.begin() + base + m_inputDim);
    }
    template<class DistanceFn>
    std::size_t SelfOrganizingMap<DistanceFn>::getWidth() const noexcept{
        return m_width;
    }
    template<class DistanceFn>
    std::size_t SelfOrganizingMap<DistanceFn>::getHeight() const noexcept{
        return m_height;
    }
    template<class DistanceFn>
    std::size_t SelfOrganizingMap<DistanceFn>::getInputDim() const noexcept{
        return m_inputDim;
    }
    template<class DistanceFn>
    JsonBox::Value SelfOrganizingMap<DistanceFn>::toJson() const{
        JsonBox::Object o;
        o["width"] = std::to_string(m_width);
        o["height"] = std::to_string(m_height);
        o["inputDim"] = std::to_string(m_inputDim);
        o["toroidal"] = JsonBox::Value(m_toroidal);
        JsonBox::Array weightsArr;
        weightsArr.reserve(m_weights.size());
        for(auto w : m_weights){
            weightsArr.push_back(JsonBox::Value(w));
        }
        o["weights"] = weightsArr;
        return o;
    }
    template<class DistanceFn>
    std::size_t SelfOrganizingMap<DistanceFn>::idx(std::size_t x, std::size_t y, std::size_t d) const noexcept{
        return (y * m_width + x) * m_inputDim + d;
    }
    template<class DistanceFn>
    double SelfOrganizingMap<DistanceFn>::gridDistance(std::size_t x1, std::size_t y1, std::size_t x2, std::size_t y2) const noexcept{
        double dx = static_cast<double>(x1 > x2 ? x1 - x2 : x2 - x1);
        double dy = static_cast<double>(y1 > y2 ? y1 - y2 : y2 - y1);
        if(m_toroidal){
            dx = std::min(dx, static_cast<double>(m_width) - dx);
            dy = std::min(dy, static_cast<double>(m_height) - dy);
        }
        return std::sqrt(dx * dx + dy * dy);
    }
    template<class DistanceFn>
    std::pair<std::size_t,std::size_t> SelfOrganizingMap<DistanceFn>::findBMU(const std::vector<double>& sample) const noexcept{
        std::size_t bestX = 0u, bestY = 0u;
        double bestDist = std::numeric_limits<double>::max();
        for(std::size_t y=0;y<m_height;++y){
            for(std::size_t x=0;x<m_width;++x){
                auto base = idx(x, y, 0);
                std::copy(m_weights.begin() + base, m_weights.begin() + base + m_inputDim, m_scratch.begin());
                auto d = m_distance(m_scratch, sample);
                if(d < bestDist){
                    bestDist = d;
                    bestX = x;
                    bestY = y;
                }
            }
        }
        return {bestX, bestY};
    }
}

#endif // EVOAI_SELF_ORGANIZING_MAP_HPP
